// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SkyRoute_Infrastructure.Context;

#nullable disable

namespace SkyRoute_Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260509093341_try2")]
    partial class try2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SkyRoute_Domain.Entities.Airport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<string>("CodeIATA")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("PublicName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("CodeIATA")
                        .IsUnique();

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CityId = 1,
                            CodeIATA = "JFK",
                            PublicName = "John F. Kennedy Intl"
                        },
                        new
                        {
                            Id = 2,
                            CityId = 2,
                            CodeIATA = "LAX",
                            PublicName = "Los Angeles Intl"
                        },
                        new
                        {
                            Id = 3,
                            CityId = 3,
                            CodeIATA = "LHR",
                            PublicName = "London Heathrow"
                        },
                        new
                        {
                            Id = 4,
                            CityId = 3,
                            CodeIATA = "LGW",
                            PublicName = "London Gatwick"
                        },
                        new
                        {
                            Id = 5,
                            CityId = 4,
                            CodeIATA = "MAN",
                            PublicName = "Manchester Airport"
                        },
                        new
                        {
                            Id = 6,
                            CityId = 1,
                            CodeIATA = "EWR",
                            PublicName = "Newark Liberty"
                        },
                        new
                        {
                            Id = 7,
                            CityId = 5,
                            CodeIATA = "EZE",
                            PublicName = "Aeropuerto Internacional Ezeiza"
                        },
                        new
                        {
                            Id = 8,
                            CityId = 6,
                            CodeIATA = "GIG",
                            PublicName = "Galeão–Antonio Carlos Jobim International Airport"
                        });
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CabinType")
                        .HasColumnType("int");

                    b.Property<DateTime>("FlightDepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("FlightId")
                        .HasColumnType("int");

                    b.Property<bool>("IsInternational")
                        .HasColumnType("bit");

                    b.Property<int>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<decimal>("PriceTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReferenceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("FlightId");

                    b.HasIndex("ReferenceCode")
                        .IsUnique();

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Cities");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            Name = "New York"
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            Name = "Los Angeles"
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            Name = "London"
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 2,
                            Name = "Manchester"
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 3,
                            Name = "Buenos Aires"
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 4,
                            Name = "Rio de Janeiro"
                        });
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "United States"
                        },
                        new
                        {
                            Id = 2,
                            Name = "United Kingdom"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Argentina"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Brasil"
                        });
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.Flight", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AirportDestinationId")
                        .HasColumnType("int");

                    b.Property<int>("AirportOriginId")
                        .HasColumnType("int");

                    b.Property<decimal>("BaseFare")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CabinType")
                        .HasColumnType("int");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProviderName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeatsFree")
                        .HasColumnType("int");

                    b.Property<int>("SeatsTotal")
                        .HasColumnType("int");

                    b.Property<DateTime>("TimeArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TimeDeparture")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AirportDestinationId");

                    b.HasIndex("AirportOriginId");

                    b.ToTable("Flights");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AirportDestinationId = 2,
                            AirportOriginId = 1,
                            BaseFare = 150.00m,
                            CabinType = 0,
                            DurationMinutes = 120,
                            FlightNumber = "BW-99",
                            ProviderName = "BudgetWings",
                            SeatsFree = 13,
                            SeatsTotal = 20,
                            TimeArrival = new DateTime(2026, 6, 1, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            TimeDeparture = new DateTime(2026, 6, 1, 10, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AirportDestinationId = 8,
                            AirportOriginId = 7,
                            BaseFare = 200.00m,
                            CabinType = 2,
                            DurationMinutes = 180,
                            FlightNumber = "GA-101",
                            ProviderName = "GlobalAir",
                            SeatsFree = 6,
                            SeatsTotal = 140,
                            TimeArrival = new DateTime(2026, 6, 2, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TimeDeparture = new DateTime(2026, 6, 2, 15, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.Passenger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BookingId")
                        .HasColumnType("int");

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsPassport")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.Airport", b =>
                {
                    b.HasOne("SkyRoute_Domain.Entities.City", "City")
                        .WithMany("Airports")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.Booking", b =>
                {
                    b.HasOne("SkyRoute_Domain.Entities.Flight", "Flight")
                        .WithMany()
                        .HasForeignKey("FlightId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Flight");
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.City", b =>
                {
                    b.HasOne("SkyRoute_Domain.Entities.Country", "Country")
                        .WithMany("Cities")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.Flight", b =>
                {
                    b.HasOne("SkyRoute_Domain.Entities.Airport", "AirportDestination")
                        .WithMany()
                        .HasForeignKey("AirportDestinationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SkyRoute_Domain.Entities.Airport", "AirportOrigin")
                        .WithMany()
                        .HasForeignKey("AirportOriginId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AirportDestination");

                    b.Navigation("AirportOrigin");
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.Passenger", b =>
                {
                    b.HasOne("SkyRoute_Domain.Entities.Booking", "Booking")
                        .WithMany("Passengers")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.Booking", b =>
                {
                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.City", b =>
                {
                    b.Navigation("Airports");
                });

            modelBuilder.Entity("SkyRoute_Domain.Entities.Country", b =>
                {
                    b.Navigation("Cities");
                });
#pragma warning restore 612, 618
        }
    }
}
